#include <stdio.h>
#include <stdlib.h>
#include <syslog.h>

/* Available logopt */
/* 
    LOG_PID         : Log the process ID with each message
    LOG_CONS        : Log to the system console on error
    LOG_NDELAY      : Connect to syslog daemon immediately
    LOG_ODELAY      : Delay open until syslog() is called
    LOG_NOWAIT      : Don't wait for child process
*/

/* Available facility */
/*
    LOG_KERN        : Reserved for message generated by the system.
    LOG_USER        : Message generated by a process.
    LOG_MAIL        : Reserved for message generated by mail system.
    LOG_NEWS        : Reserved for message generated by news system.
    LOG_UUCP        : Reserved for message generated by UUCP system.
    LOG_DAEMON      : Reserved for message generated by system daemon.
    LOG_AUTH        : Reserved for message generated by authorisation daemon.
    LOG_CRON        : Reserved for message generated by the clock daemon.
    LOG_LPR         : Reserved for message generated by printer system.
    LOG_LOCAL0      : Reserved for local use.
    LOG_LOCAL1      : Reserved for local use.
    LOG_LOCAL2      : Reserved for local use.
    LOG_LOCAL3      : Reserved for local use.
    LOG_LOCAL4      : Reserved for local use.
    LOG_LOCAL5      : Reserved for local use.
    LOG_LOCAL6      : Reserved for local use.
    LOG_LOCAL7      : Reserved for local use.
*/

/*
    The following are declared as macros for constructing the maskpri argument to setlogmask().
    The following macros expand to an expression of type int when the argument pri is an expression of type int:

    LOG_MASK(pri)   : A mask for priority pri.

    The following constants are defined as possible values for the priority argument of syslog():
    LOG_EMERG       : A panic condition was reported to all processes.
    LOG_ALERT       : A condition that should be corrected immediately.
    LOG_CRIT        : A critical condition.
    LOG_ERR         : An error message.
    LOG_WARNING     : A warning message.
    LOG_NOTICE      : A condition requiring special handling.
    LOG_INFO        : A general information message.
    LOG_DEBUG       : A message useful for debugging programs.
*/

int main(int argc, char **argv)
{
    /* To use system log, we must invoke openlog(ident, logopt, facility) first */
    openlog("hello syslog", LOG_PID | LOG_CONS, LOG_USER);

    /* optional, setlogmask could setup the priority of logging  */
    setlogmask(LOG_MASK(LOG_NOTICE) | LOG_MASK(LOG_INFO));

    /* logging */
    syslog(LOG_EMERG, "LOG_EMERG for test");
    syslog(LOG_NOTICE, "LOG_NOTICE for test");
    syslog(LOG_INFO, "LOG_INFO for test");
    syslog(LOG_DEBUG, "LOG_DEBUG for test");

    /* close the syslog */
    closelog();

    return 0;
}