.PHONY: all clean

CC                := gcc

PROGRESS_BAR_PROG := progress_bar
PROGRESS_BAR_SRCS := progress_bar.c

all: 
	$(CC) -o $(PROGRESS_BAR_PROG) $(PROGRESS_BAR_SRCS)

clean:
	rm $(PROGRESS_BAR_PROG)