.PHONY: all clean

CC := gcc
PTR_STRUCT_FILE := ptr_struct_file

all: all_ptr_struct_file

all_ptr_struct_file:
	$(CC) -o $(PTR_STRUCT_FILE) $(PTR_STRUCT_FILE).c

clean: clean_ptr_struct_file

clean_ptr_struct_file:
	rm $(PTR_STRUCT_FILE)
